/********************************************************************************
** Form generated from reading UI file 'senso_stick.ui'
**
** Created by: Qt User Interface Compiler version 5.12.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SENSO_STICK_H
#define UI_SENSO_STICK_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Senso_Stick
{
public:
    QWidget *centralWidget;
    QLabel *CAN_init_label;
    QLabel *CAN_status_label;
    QLabel *CAN_communication_test_label;
    QCheckBox *CAN_status_checkBox;
    QCheckBox *CAN_communication_test_1_checkBox;
    QLabel *CAN_status_Error_label;
    QLabel *CAN_communication_Error_1_label;
    QLabel *CAN_init_Error_label;
    QPushButton *Start_pushButton;
    QPushButton *Stop_Peak_CANpushButton;
    QLabel *Status_label;
    QLabel *Error_label;
    QFrame *line;
    QFrame *line_2;
    QLabel *State_label;
    QLabel *Statemachine_label;
    QPushButton *Check_Motorencoder_pushButton;
    QLabel *Motorencoderpos_1_label;
    QLabel *Motorencoderpos_value_1_label;
    QFrame *line_3;
    QFrame *line_4;
    QPushButton *ReferenceDrive_pushButton;
    QLabel *Encoder_Index_1_label;
    QLabel *Encoder_Indexvalue_1_label;
    QFrame *line_5;
    QFrame *line_6;
    QPushButton *Normal_Mode_Off_pushButton;
    QCheckBox *CAN_init_checkBox;
    QFrame *line_7;
    QLabel *Peak_CAN_start_label;
    QPushButton *Stop_Senso_Stick_pushButton;
    QLabel *Senso_Stick_label;
    QPushButton *SensoStick_CAN_Comm_pushButton;
    QFrame *line_8;
    QFrame *line_9;
    QCheckBox *CAN_communication_test_2_checkBox;
    QCheckBox *CAN_communication_test_3_checkBox;
    QLabel *CAN_communication_Error_2_label;
    QLabel *CAN_communication_Error_3_label;
    QLabel *Motorencoderpos_2_label;
    QLabel *Motorencoderpos_3_label;
    QLabel *Motorencoderpos_value_2_label;
    QLabel *Motorencoderpos_value_3_label;
    QLabel *Encoder_Index_2_label;
    QLabel *Encoder_Index_3_label;
    QLabel *Encoder_Indexvalue_2_label;
    QLabel *Encoder_Indexvalue_3_label;
    QFrame *line_10;
    QTextBrowser *Status_textBrowser;
    QTextBrowser *Error_textBrowser;
    QPushButton *Clear_Status_pushButton;
    QPushButton *Clear_Error_pushButton;
    QPushButton *Normal_Mode_Ready_pushButton;
    QPushButton *Normal_Mode_On_pushButton;
    QLabel *Enable_Button_label;
    QPushButton *Normal_Mode_Spring_Damper_pushButton;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QLabel *y_Spring_Stiffness_label;
    QSlider *y_Spring_Stiffness_horizontalSlider;
    QLabel *y_Friction_label;
    QSlider *y_Friction_horizontalSlider;
    QLabel *y_Damping_label;
    QSlider *y_Damping_horizontalSlider;
    QLabel *y_Torque_label;
    QSlider *y_Torque_horizontalSlider;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QFrame *line_21;
    QFrame *line_22;
    QLabel *Torque_Limit_label;
    QLabel *Peak_Torque_Limit_label;
    QSlider *Torque_Limit_horizontalSlider;
    QSlider *Peak_Torque_Limit_horizontalSlider;
    QLabel *Torque_Limit_value_label;
    QLabel *Peak_Torque_Limit_value_label;
    QLabel *General_Torque_label;
    QFrame *line_23;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QRadioButton *Mini_Stick_left_radioButton;
    QRadioButton *Mini_Stick_middle_radioButton;
    QRadioButton *Mini_Stick_right_radioButton;
    QRadioButton *Mini_Stick_up_radioButton;
    QRadioButton *Mini_Stick_down_radioButton;
    QRadioButton *Flip_Switch_left_radioButton;
    QRadioButton *Flip_Switch_middle_radioButton;
    QRadioButton *Flip_Switch_right_radioButton;
    QRadioButton *Front_Button_radioButton;
    QRadioButton *Enable_Button_radioButton;
    QLabel *Front_label;
    QLabel *Rear_label;
    QLabel *y_settings_label;
    QSlider *x_Spring_Stiffness_horizontalSlider;
    QLabel *x_Torque_label;
    QFrame *line_27;
    QSlider *x_Torque_horizontalSlider;
    QLabel *x_Friction_label;
    QFrame *line_28;
    QFrame *line_29;
    QSlider *x_Friction_horizontalSlider;
    QLabel *x_Spring_Stiffness_label;
    QLabel *x_Damping_label;
    QFrame *line_30;
    QLabel *x_settings_label;
    QSlider *x_Damping_horizontalSlider;
    QFrame *line_31;
    QFrame *line_32;
    QSlider *z_Friction_horizontalSlider;
    QLabel *z_Friction_label;
    QLabel *z_Spring_Stiffness_label;
    QSlider *z_Spring_Stiffness_horizontalSlider;
    QFrame *line_33;
    QSlider *z_Damping_horizontalSlider;
    QLabel *z_Damping_label;
    QLabel *z_settings_label;
    QLabel *z_Torque_label;
    QSlider *z_Torque_horizontalSlider;
    QFrame *line_34;
    QRadioButton *switch_off_acknowledge_button_radioButton;
    QRadioButton *external_control_radioButton;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *Senso_Stick)
    {
        if (Senso_Stick->objectName().isEmpty())
            Senso_Stick->setObjectName(QString::fromUtf8("Senso_Stick"));
        Senso_Stick->resize(1430, 1024);
        centralWidget = new QWidget(Senso_Stick);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        CAN_init_label = new QLabel(centralWidget);
        CAN_init_label->setObjectName(QString::fromUtf8("CAN_init_label"));
        CAN_init_label->setGeometry(QRect(110, 20, 141, 16));
        CAN_status_label = new QLabel(centralWidget);
        CAN_status_label->setObjectName(QString::fromUtf8("CAN_status_label"));
        CAN_status_label->setGeometry(QRect(110, 50, 141, 16));
        CAN_communication_test_label = new QLabel(centralWidget);
        CAN_communication_test_label->setObjectName(QString::fromUtf8("CAN_communication_test_label"));
        CAN_communication_test_label->setGeometry(QRect(110, 80, 141, 16));
        CAN_status_checkBox = new QCheckBox(centralWidget);
        CAN_status_checkBox->setObjectName(QString::fromUtf8("CAN_status_checkBox"));
        CAN_status_checkBox->setGeometry(QRect(260, 50, 70, 17));
        CAN_communication_test_1_checkBox = new QCheckBox(centralWidget);
        CAN_communication_test_1_checkBox->setObjectName(QString::fromUtf8("CAN_communication_test_1_checkBox"));
        CAN_communication_test_1_checkBox->setGeometry(QRect(160, 120, 70, 17));
        CAN_status_Error_label = new QLabel(centralWidget);
        CAN_status_Error_label->setObjectName(QString::fromUtf8("CAN_status_Error_label"));
        CAN_status_Error_label->setGeometry(QRect(360, 50, 47, 13));
        CAN_communication_Error_1_label = new QLabel(centralWidget);
        CAN_communication_Error_1_label->setObjectName(QString::fromUtf8("CAN_communication_Error_1_label"));
        CAN_communication_Error_1_label->setGeometry(QRect(260, 120, 101, 16));
        CAN_init_Error_label = new QLabel(centralWidget);
        CAN_init_Error_label->setObjectName(QString::fromUtf8("CAN_init_Error_label"));
        CAN_init_Error_label->setGeometry(QRect(360, 20, 47, 13));
        Start_pushButton = new QPushButton(centralWidget);
        Start_pushButton->setObjectName(QString::fromUtf8("Start_pushButton"));
        Start_pushButton->setGeometry(QRect(10, 40, 91, 23));
        Stop_Peak_CANpushButton = new QPushButton(centralWidget);
        Stop_Peak_CANpushButton->setObjectName(QString::fromUtf8("Stop_Peak_CANpushButton"));
        Stop_Peak_CANpushButton->setGeometry(QRect(1280, 40, 111, 21));
        Status_label = new QLabel(centralWidget);
        Status_label->setObjectName(QString::fromUtf8("Status_label"));
        Status_label->setGeometry(QRect(430, 660, 47, 13));
        Error_label = new QLabel(centralWidget);
        Error_label->setObjectName(QString::fromUtf8("Error_label"));
        Error_label->setGeometry(QRect(910, 660, 47, 13));
        line = new QFrame(centralWidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(20, 100, 421, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(440, 40, 20, 51));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        State_label = new QLabel(centralWidget);
        State_label->setObjectName(QString::fromUtf8("State_label"));
        State_label->setGeometry(QRect(570, 140, 71, 21));
        Statemachine_label = new QLabel(centralWidget);
        Statemachine_label->setObjectName(QString::fromUtf8("Statemachine_label"));
        Statemachine_label->setGeometry(QRect(650, 140, 61, 21));
        Check_Motorencoder_pushButton = new QPushButton(centralWidget);
        Check_Motorencoder_pushButton->setObjectName(QString::fromUtf8("Check_Motorencoder_pushButton"));
        Check_Motorencoder_pushButton->setGeometry(QRect(10, 260, 131, 23));
        Motorencoderpos_1_label = new QLabel(centralWidget);
        Motorencoderpos_1_label->setObjectName(QString::fromUtf8("Motorencoderpos_1_label"));
        Motorencoderpos_1_label->setGeometry(QRect(70, 702, 151, 21));
        Motorencoderpos_value_1_label = new QLabel(centralWidget);
        Motorencoderpos_value_1_label->setObjectName(QString::fromUtf8("Motorencoderpos_value_1_label"));
        Motorencoderpos_value_1_label->setGeometry(QRect(240, 701, 121, 21));
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(20, 320, 421, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(350, 700, 20, 81));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        ReferenceDrive_pushButton = new QPushButton(centralWidget);
        ReferenceDrive_pushButton->setObjectName(QString::fromUtf8("ReferenceDrive_pushButton"));
        ReferenceDrive_pushButton->setGeometry(QRect(10, 370, 131, 23));
        Encoder_Index_1_label = new QLabel(centralWidget);
        Encoder_Index_1_label->setObjectName(QString::fromUtf8("Encoder_Index_1_label"));
        Encoder_Index_1_label->setGeometry(QRect(160, 350, 101, 16));
        Encoder_Indexvalue_1_label = new QLabel(centralWidget);
        Encoder_Indexvalue_1_label->setObjectName(QString::fromUtf8("Encoder_Indexvalue_1_label"));
        Encoder_Indexvalue_1_label->setGeometry(QRect(270, 350, 101, 16));
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(20, 430, 421, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(440, 340, 20, 91));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        Normal_Mode_Off_pushButton = new QPushButton(centralWidget);
        Normal_Mode_Off_pushButton->setObjectName(QString::fromUtf8("Normal_Mode_Off_pushButton"));
        Normal_Mode_Off_pushButton->setGeometry(QRect(250, 570, 131, 23));
        CAN_init_checkBox = new QCheckBox(centralWidget);
        CAN_init_checkBox->setObjectName(QString::fromUtf8("CAN_init_checkBox"));
        CAN_init_checkBox->setGeometry(QRect(260, 20, 70, 17));
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(460, 100, 941, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        Peak_CAN_start_label = new QLabel(centralWidget);
        Peak_CAN_start_label->setObjectName(QString::fromUtf8("Peak_CAN_start_label"));
        Peak_CAN_start_label->setGeometry(QRect(430, 10, 91, 21));
        Stop_Senso_Stick_pushButton = new QPushButton(centralWidget);
        Stop_Senso_Stick_pushButton->setObjectName(QString::fromUtf8("Stop_Senso_Stick_pushButton"));
        Stop_Senso_Stick_pushButton->setGeometry(QRect(1280, 150, 121, 21));
        Senso_Stick_label = new QLabel(centralWidget);
        Senso_Stick_label->setObjectName(QString::fromUtf8("Senso_Stick_label"));
        Senso_Stick_label->setGeometry(QRect(430, 120, 71, 21));
        SensoStick_CAN_Comm_pushButton = new QPushButton(centralWidget);
        SensoStick_CAN_Comm_pushButton->setObjectName(QString::fromUtf8("SensoStick_CAN_Comm_pushButton"));
        SensoStick_CAN_Comm_pushButton->setGeometry(QRect(10, 150, 131, 21));
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(20, 210, 421, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(440, 150, 20, 61));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        CAN_communication_test_2_checkBox = new QCheckBox(centralWidget);
        CAN_communication_test_2_checkBox->setObjectName(QString::fromUtf8("CAN_communication_test_2_checkBox"));
        CAN_communication_test_2_checkBox->setGeometry(QRect(160, 150, 70, 17));
        CAN_communication_test_3_checkBox = new QCheckBox(centralWidget);
        CAN_communication_test_3_checkBox->setObjectName(QString::fromUtf8("CAN_communication_test_3_checkBox"));
        CAN_communication_test_3_checkBox->setGeometry(QRect(160, 180, 70, 17));
        CAN_communication_Error_2_label = new QLabel(centralWidget);
        CAN_communication_Error_2_label->setObjectName(QString::fromUtf8("CAN_communication_Error_2_label"));
        CAN_communication_Error_2_label->setGeometry(QRect(260, 150, 101, 16));
        CAN_communication_Error_3_label = new QLabel(centralWidget);
        CAN_communication_Error_3_label->setObjectName(QString::fromUtf8("CAN_communication_Error_3_label"));
        CAN_communication_Error_3_label->setGeometry(QRect(260, 180, 101, 16));
        Motorencoderpos_2_label = new QLabel(centralWidget);
        Motorencoderpos_2_label->setObjectName(QString::fromUtf8("Motorencoderpos_2_label"));
        Motorencoderpos_2_label->setGeometry(QRect(70, 730, 151, 21));
        Motorencoderpos_3_label = new QLabel(centralWidget);
        Motorencoderpos_3_label->setObjectName(QString::fromUtf8("Motorencoderpos_3_label"));
        Motorencoderpos_3_label->setGeometry(QRect(70, 760, 151, 21));
        Motorencoderpos_value_2_label = new QLabel(centralWidget);
        Motorencoderpos_value_2_label->setObjectName(QString::fromUtf8("Motorencoderpos_value_2_label"));
        Motorencoderpos_value_2_label->setGeometry(QRect(240, 730, 121, 21));
        Motorencoderpos_value_3_label = new QLabel(centralWidget);
        Motorencoderpos_value_3_label->setObjectName(QString::fromUtf8("Motorencoderpos_value_3_label"));
        Motorencoderpos_value_3_label->setGeometry(QRect(240, 760, 121, 21));
        Encoder_Index_2_label = new QLabel(centralWidget);
        Encoder_Index_2_label->setObjectName(QString::fromUtf8("Encoder_Index_2_label"));
        Encoder_Index_2_label->setGeometry(QRect(160, 380, 101, 16));
        Encoder_Index_3_label = new QLabel(centralWidget);
        Encoder_Index_3_label->setObjectName(QString::fromUtf8("Encoder_Index_3_label"));
        Encoder_Index_3_label->setGeometry(QRect(160, 410, 101, 16));
        Encoder_Indexvalue_2_label = new QLabel(centralWidget);
        Encoder_Indexvalue_2_label->setObjectName(QString::fromUtf8("Encoder_Indexvalue_2_label"));
        Encoder_Indexvalue_2_label->setGeometry(QRect(270, 380, 101, 16));
        Encoder_Indexvalue_3_label = new QLabel(centralWidget);
        Encoder_Indexvalue_3_label->setObjectName(QString::fromUtf8("Encoder_Indexvalue_3_label"));
        Encoder_Indexvalue_3_label->setGeometry(QRect(270, 410, 101, 16));
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(30, 640, 1371, 16));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        Status_textBrowser = new QTextBrowser(centralWidget);
        Status_textBrowser->setObjectName(QString::fromUtf8("Status_textBrowser"));
        Status_textBrowser->setGeometry(QRect(490, 660, 321, 271));
        Error_textBrowser = new QTextBrowser(centralWidget);
        Error_textBrowser->setObjectName(QString::fromUtf8("Error_textBrowser"));
        Error_textBrowser->setGeometry(QRect(970, 660, 321, 271));
        Clear_Status_pushButton = new QPushButton(centralWidget);
        Clear_Status_pushButton->setObjectName(QString::fromUtf8("Clear_Status_pushButton"));
        Clear_Status_pushButton->setGeometry(QRect(570, 940, 151, 23));
        Clear_Error_pushButton = new QPushButton(centralWidget);
        Clear_Error_pushButton->setObjectName(QString::fromUtf8("Clear_Error_pushButton"));
        Clear_Error_pushButton->setGeometry(QRect(1060, 940, 151, 23));
        Normal_Mode_Ready_pushButton = new QPushButton(centralWidget);
        Normal_Mode_Ready_pushButton->setObjectName(QString::fromUtf8("Normal_Mode_Ready_pushButton"));
        Normal_Mode_Ready_pushButton->setGeometry(QRect(390, 570, 131, 23));
        Normal_Mode_On_pushButton = new QPushButton(centralWidget);
        Normal_Mode_On_pushButton->setObjectName(QString::fromUtf8("Normal_Mode_On_pushButton"));
        Normal_Mode_On_pushButton->setGeometry(QRect(530, 570, 131, 23));
        Enable_Button_label = new QLabel(centralWidget);
        Enable_Button_label->setObjectName(QString::fromUtf8("Enable_Button_label"));
        Enable_Button_label->setGeometry(QRect(520, 530, 151, 20));
        Normal_Mode_Spring_Damper_pushButton = new QPushButton(centralWidget);
        Normal_Mode_Spring_Damper_pushButton->setObjectName(QString::fromUtf8("Normal_Mode_Spring_Damper_pushButton"));
        Normal_Mode_Spring_Damper_pushButton->setGeometry(QRect(680, 570, 171, 23));
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(480, 220, 20, 291));
        line_11->setFrameShape(QFrame::VLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralWidget);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setGeometry(QRect(770, 220, 20, 291));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(centralWidget);
        line_13->setObjectName(QString::fromUtf8("line_13"));
        line_13->setGeometry(QRect(490, 210, 291, 20));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralWidget);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setGeometry(QRect(490, 500, 291, 20));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        y_Spring_Stiffness_label = new QLabel(centralWidget);
        y_Spring_Stiffness_label->setObjectName(QString::fromUtf8("y_Spring_Stiffness_label"));
        y_Spring_Stiffness_label->setGeometry(QRect(500, 280, 161, 16));
        y_Spring_Stiffness_horizontalSlider = new QSlider(centralWidget);
        y_Spring_Stiffness_horizontalSlider->setObjectName(QString::fromUtf8("y_Spring_Stiffness_horizontalSlider"));
        y_Spring_Stiffness_horizontalSlider->setGeometry(QRect(610, 300, 160, 19));
        y_Spring_Stiffness_horizontalSlider->setOrientation(Qt::Horizontal);
        y_Friction_label = new QLabel(centralWidget);
        y_Friction_label->setObjectName(QString::fromUtf8("y_Friction_label"));
        y_Friction_label->setGeometry(QRect(500, 340, 161, 16));
        y_Friction_horizontalSlider = new QSlider(centralWidget);
        y_Friction_horizontalSlider->setObjectName(QString::fromUtf8("y_Friction_horizontalSlider"));
        y_Friction_horizontalSlider->setGeometry(QRect(610, 360, 160, 19));
        y_Friction_horizontalSlider->setOrientation(Qt::Horizontal);
        y_Damping_label = new QLabel(centralWidget);
        y_Damping_label->setObjectName(QString::fromUtf8("y_Damping_label"));
        y_Damping_label->setGeometry(QRect(500, 400, 161, 16));
        y_Damping_horizontalSlider = new QSlider(centralWidget);
        y_Damping_horizontalSlider->setObjectName(QString::fromUtf8("y_Damping_horizontalSlider"));
        y_Damping_horizontalSlider->setGeometry(QRect(610, 420, 160, 19));
        y_Damping_horizontalSlider->setOrientation(Qt::Horizontal);
        y_Torque_label = new QLabel(centralWidget);
        y_Torque_label->setObjectName(QString::fromUtf8("y_Torque_label"));
        y_Torque_label->setGeometry(QRect(500, 460, 161, 16));
        y_Torque_horizontalSlider = new QSlider(centralWidget);
        y_Torque_horizontalSlider->setObjectName(QString::fromUtf8("y_Torque_horizontalSlider"));
        y_Torque_horizontalSlider->setGeometry(QRect(610, 480, 160, 19));
        y_Torque_horizontalSlider->setOrientation(Qt::Horizontal);
        line_15 = new QFrame(centralWidget);
        line_15->setObjectName(QString::fromUtf8("line_15"));
        line_15->setGeometry(QRect(440, 230, 20, 81));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(centralWidget);
        line_16->setObjectName(QString::fromUtf8("line_16"));
        line_16->setGeometry(QRect(50, 790, 301, 20));
        line_16->setFrameShape(QFrame::HLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(centralWidget);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setGeometry(QRect(50, 680, 301, 20));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(centralWidget);
        line_18->setObjectName(QString::fromUtf8("line_18"));
        line_18->setGeometry(QRect(20, 700, 20, 81));
        line_18->setFrameShape(QFrame::VLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(centralWidget);
        line_19->setObjectName(QString::fromUtf8("line_19"));
        line_19->setGeometry(QRect(30, 700, 20, 81));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(centralWidget);
        line_20->setObjectName(QString::fromUtf8("line_20"));
        line_20->setGeometry(QRect(360, 700, 20, 81));
        line_20->setFrameShape(QFrame::VLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_21 = new QFrame(centralWidget);
        line_21->setObjectName(QString::fromUtf8("line_21"));
        line_21->setGeometry(QRect(50, 780, 301, 20));
        line_21->setFrameShape(QFrame::HLine);
        line_21->setFrameShadow(QFrame::Sunken);
        line_22 = new QFrame(centralWidget);
        line_22->setObjectName(QString::fromUtf8("line_22"));
        line_22->setGeometry(QRect(50, 690, 301, 20));
        line_22->setFrameShape(QFrame::HLine);
        line_22->setFrameShadow(QFrame::Sunken);
        Torque_Limit_label = new QLabel(centralWidget);
        Torque_Limit_label->setObjectName(QString::fromUtf8("Torque_Limit_label"));
        Torque_Limit_label->setGeometry(QRect(50, 480, 171, 16));
        Peak_Torque_Limit_label = new QLabel(centralWidget);
        Peak_Torque_Limit_label->setObjectName(QString::fromUtf8("Peak_Torque_Limit_label"));
        Peak_Torque_Limit_label->setGeometry(QRect(50, 560, 181, 16));
        Torque_Limit_horizontalSlider = new QSlider(centralWidget);
        Torque_Limit_horizontalSlider->setObjectName(QString::fromUtf8("Torque_Limit_horizontalSlider"));
        Torque_Limit_horizontalSlider->setGeometry(QRect(50, 530, 160, 19));
        Torque_Limit_horizontalSlider->setOrientation(Qt::Horizontal);
        Peak_Torque_Limit_horizontalSlider = new QSlider(centralWidget);
        Peak_Torque_Limit_horizontalSlider->setObjectName(QString::fromUtf8("Peak_Torque_Limit_horizontalSlider"));
        Peak_Torque_Limit_horizontalSlider->setGeometry(QRect(50, 610, 160, 19));
        Peak_Torque_Limit_horizontalSlider->setOrientation(Qt::Horizontal);
        Torque_Limit_value_label = new QLabel(centralWidget);
        Torque_Limit_value_label->setObjectName(QString::fromUtf8("Torque_Limit_value_label"));
        Torque_Limit_value_label->setGeometry(QRect(150, 500, 51, 16));
        Peak_Torque_Limit_value_label = new QLabel(centralWidget);
        Peak_Torque_Limit_value_label->setObjectName(QString::fromUtf8("Peak_Torque_Limit_value_label"));
        Peak_Torque_Limit_value_label->setGeometry(QRect(150, 580, 51, 16));
        General_Torque_label = new QLabel(centralWidget);
        General_Torque_label->setObjectName(QString::fromUtf8("General_Torque_label"));
        General_Torque_label->setGeometry(QRect(100, 450, 81, 16));
        line_23 = new QFrame(centralWidget);
        line_23->setObjectName(QString::fromUtf8("line_23"));
        line_23->setGeometry(QRect(210, 470, 20, 171));
        line_23->setFrameShape(QFrame::VLine);
        line_23->setFrameShadow(QFrame::Sunken);
        line_24 = new QFrame(centralWidget);
        line_24->setObjectName(QString::fromUtf8("line_24"));
        line_24->setGeometry(QRect(30, 460, 191, 20));
        line_24->setFrameShape(QFrame::HLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(centralWidget);
        line_25->setObjectName(QString::fromUtf8("line_25"));
        line_25->setGeometry(QRect(20, 470, 20, 171));
        line_25->setFrameShape(QFrame::VLine);
        line_25->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(centralWidget);
        line_26->setObjectName(QString::fromUtf8("line_26"));
        line_26->setGeometry(QRect(30, 630, 191, 20));
        line_26->setFrameShape(QFrame::HLine);
        line_26->setFrameShadow(QFrame::Sunken);
        Mini_Stick_left_radioButton = new QRadioButton(centralWidget);
        Mini_Stick_left_radioButton->setObjectName(QString::fromUtf8("Mini_Stick_left_radioButton"));
        Mini_Stick_left_radioButton->setGeometry(QRect(140, 870, 16, 17));
        Mini_Stick_middle_radioButton = new QRadioButton(centralWidget);
        Mini_Stick_middle_radioButton->setObjectName(QString::fromUtf8("Mini_Stick_middle_radioButton"));
        Mini_Stick_middle_radioButton->setGeometry(QRect(160, 870, 16, 17));
        Mini_Stick_right_radioButton = new QRadioButton(centralWidget);
        Mini_Stick_right_radioButton->setObjectName(QString::fromUtf8("Mini_Stick_right_radioButton"));
        Mini_Stick_right_radioButton->setGeometry(QRect(180, 870, 16, 17));
        Mini_Stick_up_radioButton = new QRadioButton(centralWidget);
        Mini_Stick_up_radioButton->setObjectName(QString::fromUtf8("Mini_Stick_up_radioButton"));
        Mini_Stick_up_radioButton->setGeometry(QRect(160, 850, 16, 17));
        Mini_Stick_down_radioButton = new QRadioButton(centralWidget);
        Mini_Stick_down_radioButton->setObjectName(QString::fromUtf8("Mini_Stick_down_radioButton"));
        Mini_Stick_down_radioButton->setGeometry(QRect(160, 890, 16, 17));
        Flip_Switch_left_radioButton = new QRadioButton(centralWidget);
        Flip_Switch_left_radioButton->setObjectName(QString::fromUtf8("Flip_Switch_left_radioButton"));
        Flip_Switch_left_radioButton->setGeometry(QRect(40, 870, 16, 17));
        Flip_Switch_middle_radioButton = new QRadioButton(centralWidget);
        Flip_Switch_middle_radioButton->setObjectName(QString::fromUtf8("Flip_Switch_middle_radioButton"));
        Flip_Switch_middle_radioButton->setGeometry(QRect(60, 870, 16, 17));
        Flip_Switch_right_radioButton = new QRadioButton(centralWidget);
        Flip_Switch_right_radioButton->setObjectName(QString::fromUtf8("Flip_Switch_right_radioButton"));
        Flip_Switch_right_radioButton->setGeometry(QRect(80, 870, 16, 17));
        Front_Button_radioButton = new QRadioButton(centralWidget);
        Front_Button_radioButton->setObjectName(QString::fromUtf8("Front_Button_radioButton"));
        Front_Button_radioButton->setGeometry(QRect(110, 940, 16, 17));
        Enable_Button_radioButton = new QRadioButton(centralWidget);
        Enable_Button_radioButton->setObjectName(QString::fromUtf8("Enable_Button_radioButton"));
        Enable_Button_radioButton->setGeometry(QRect(320, 880, 16, 17));
        Front_label = new QLabel(centralWidget);
        Front_label->setObjectName(QString::fromUtf8("Front_label"));
        Front_label->setGeometry(QRect(100, 820, 47, 13));
        Rear_label = new QLabel(centralWidget);
        Rear_label->setObjectName(QString::fromUtf8("Rear_label"));
        Rear_label->setGeometry(QRect(310, 820, 47, 13));
        y_settings_label = new QLabel(centralWidget);
        y_settings_label->setObjectName(QString::fromUtf8("y_settings_label"));
        y_settings_label->setGeometry(QRect(600, 230, 131, 21));
        x_Spring_Stiffness_horizontalSlider = new QSlider(centralWidget);
        x_Spring_Stiffness_horizontalSlider->setObjectName(QString::fromUtf8("x_Spring_Stiffness_horizontalSlider"));
        x_Spring_Stiffness_horizontalSlider->setGeometry(QRect(920, 300, 160, 19));
        x_Spring_Stiffness_horizontalSlider->setOrientation(Qt::Horizontal);
        x_Torque_label = new QLabel(centralWidget);
        x_Torque_label->setObjectName(QString::fromUtf8("x_Torque_label"));
        x_Torque_label->setGeometry(QRect(810, 460, 161, 16));
        line_27 = new QFrame(centralWidget);
        line_27->setObjectName(QString::fromUtf8("line_27"));
        line_27->setGeometry(QRect(1080, 220, 20, 291));
        line_27->setFrameShape(QFrame::VLine);
        line_27->setFrameShadow(QFrame::Sunken);
        x_Torque_horizontalSlider = new QSlider(centralWidget);
        x_Torque_horizontalSlider->setObjectName(QString::fromUtf8("x_Torque_horizontalSlider"));
        x_Torque_horizontalSlider->setGeometry(QRect(920, 480, 160, 19));
        x_Torque_horizontalSlider->setOrientation(Qt::Horizontal);
        x_Friction_label = new QLabel(centralWidget);
        x_Friction_label->setObjectName(QString::fromUtf8("x_Friction_label"));
        x_Friction_label->setGeometry(QRect(810, 340, 161, 16));
        line_28 = new QFrame(centralWidget);
        line_28->setObjectName(QString::fromUtf8("line_28"));
        line_28->setGeometry(QRect(790, 220, 20, 291));
        line_28->setFrameShape(QFrame::VLine);
        line_28->setFrameShadow(QFrame::Sunken);
        line_29 = new QFrame(centralWidget);
        line_29->setObjectName(QString::fromUtf8("line_29"));
        line_29->setGeometry(QRect(800, 500, 291, 20));
        line_29->setFrameShape(QFrame::HLine);
        line_29->setFrameShadow(QFrame::Sunken);
        x_Friction_horizontalSlider = new QSlider(centralWidget);
        x_Friction_horizontalSlider->setObjectName(QString::fromUtf8("x_Friction_horizontalSlider"));
        x_Friction_horizontalSlider->setGeometry(QRect(920, 360, 160, 19));
        x_Friction_horizontalSlider->setOrientation(Qt::Horizontal);
        x_Spring_Stiffness_label = new QLabel(centralWidget);
        x_Spring_Stiffness_label->setObjectName(QString::fromUtf8("x_Spring_Stiffness_label"));
        x_Spring_Stiffness_label->setGeometry(QRect(810, 280, 161, 16));
        x_Damping_label = new QLabel(centralWidget);
        x_Damping_label->setObjectName(QString::fromUtf8("x_Damping_label"));
        x_Damping_label->setGeometry(QRect(810, 400, 161, 16));
        line_30 = new QFrame(centralWidget);
        line_30->setObjectName(QString::fromUtf8("line_30"));
        line_30->setGeometry(QRect(800, 210, 291, 20));
        line_30->setFrameShape(QFrame::HLine);
        line_30->setFrameShadow(QFrame::Sunken);
        x_settings_label = new QLabel(centralWidget);
        x_settings_label->setObjectName(QString::fromUtf8("x_settings_label"));
        x_settings_label->setGeometry(QRect(910, 230, 131, 21));
        x_Damping_horizontalSlider = new QSlider(centralWidget);
        x_Damping_horizontalSlider->setObjectName(QString::fromUtf8("x_Damping_horizontalSlider"));
        x_Damping_horizontalSlider->setGeometry(QRect(920, 420, 160, 19));
        x_Damping_horizontalSlider->setOrientation(Qt::Horizontal);
        line_31 = new QFrame(centralWidget);
        line_31->setObjectName(QString::fromUtf8("line_31"));
        line_31->setGeometry(QRect(1100, 220, 20, 291));
        line_31->setFrameShape(QFrame::VLine);
        line_31->setFrameShadow(QFrame::Sunken);
        line_32 = new QFrame(centralWidget);
        line_32->setObjectName(QString::fromUtf8("line_32"));
        line_32->setGeometry(QRect(1110, 500, 291, 20));
        line_32->setFrameShape(QFrame::HLine);
        line_32->setFrameShadow(QFrame::Sunken);
        z_Friction_horizontalSlider = new QSlider(centralWidget);
        z_Friction_horizontalSlider->setObjectName(QString::fromUtf8("z_Friction_horizontalSlider"));
        z_Friction_horizontalSlider->setGeometry(QRect(1230, 360, 160, 19));
        z_Friction_horizontalSlider->setOrientation(Qt::Horizontal);
        z_Friction_label = new QLabel(centralWidget);
        z_Friction_label->setObjectName(QString::fromUtf8("z_Friction_label"));
        z_Friction_label->setGeometry(QRect(1120, 340, 161, 16));
        z_Spring_Stiffness_label = new QLabel(centralWidget);
        z_Spring_Stiffness_label->setObjectName(QString::fromUtf8("z_Spring_Stiffness_label"));
        z_Spring_Stiffness_label->setGeometry(QRect(1120, 280, 161, 16));
        z_Spring_Stiffness_horizontalSlider = new QSlider(centralWidget);
        z_Spring_Stiffness_horizontalSlider->setObjectName(QString::fromUtf8("z_Spring_Stiffness_horizontalSlider"));
        z_Spring_Stiffness_horizontalSlider->setGeometry(QRect(1230, 300, 160, 19));
        z_Spring_Stiffness_horizontalSlider->setOrientation(Qt::Horizontal);
        line_33 = new QFrame(centralWidget);
        line_33->setObjectName(QString::fromUtf8("line_33"));
        line_33->setGeometry(QRect(1110, 210, 291, 20));
        line_33->setFrameShape(QFrame::HLine);
        line_33->setFrameShadow(QFrame::Sunken);
        z_Damping_horizontalSlider = new QSlider(centralWidget);
        z_Damping_horizontalSlider->setObjectName(QString::fromUtf8("z_Damping_horizontalSlider"));
        z_Damping_horizontalSlider->setGeometry(QRect(1230, 420, 160, 19));
        z_Damping_horizontalSlider->setOrientation(Qt::Horizontal);
        z_Damping_label = new QLabel(centralWidget);
        z_Damping_label->setObjectName(QString::fromUtf8("z_Damping_label"));
        z_Damping_label->setGeometry(QRect(1120, 400, 161, 16));
        z_settings_label = new QLabel(centralWidget);
        z_settings_label->setObjectName(QString::fromUtf8("z_settings_label"));
        z_settings_label->setGeometry(QRect(1220, 230, 131, 21));
        z_Torque_label = new QLabel(centralWidget);
        z_Torque_label->setObjectName(QString::fromUtf8("z_Torque_label"));
        z_Torque_label->setGeometry(QRect(1120, 460, 161, 16));
        z_Torque_horizontalSlider = new QSlider(centralWidget);
        z_Torque_horizontalSlider->setObjectName(QString::fromUtf8("z_Torque_horizontalSlider"));
        z_Torque_horizontalSlider->setGeometry(QRect(1230, 480, 160, 19));
        z_Torque_horizontalSlider->setOrientation(Qt::Horizontal);
        line_34 = new QFrame(centralWidget);
        line_34->setObjectName(QString::fromUtf8("line_34"));
        line_34->setGeometry(QRect(1390, 220, 20, 291));
        line_34->setFrameShape(QFrame::VLine);
        line_34->setFrameShadow(QFrame::Sunken);
        switch_off_acknowledge_button_radioButton = new QRadioButton(centralWidget);
        switch_off_acknowledge_button_radioButton->setObjectName(QString::fromUtf8("switch_off_acknowledge_button_radioButton"));
        switch_off_acknowledge_button_radioButton->setGeometry(QRect(250, 530, 231, 17));
        external_control_radioButton = new QRadioButton(centralWidget);
        external_control_radioButton->setObjectName(QString::fromUtf8("external_control_radioButton"));
        external_control_radioButton->setGeometry(QRect(1070, 570, 201, 17));
        Senso_Stick->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(Senso_Stick);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1430, 21));
        Senso_Stick->setMenuBar(menuBar);
        mainToolBar = new QToolBar(Senso_Stick);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        Senso_Stick->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(Senso_Stick);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        Senso_Stick->setStatusBar(statusBar);

        retranslateUi(Senso_Stick);

        QMetaObject::connectSlotsByName(Senso_Stick);
    } // setupUi

    void retranslateUi(QMainWindow *Senso_Stick)
    {
        Senso_Stick->setWindowTitle(QApplication::translate("Senso_Stick", "Senso_Stick", nullptr));
        CAN_init_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        CAN_status_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        CAN_communication_test_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        CAN_status_checkBox->setText(QApplication::translate("Senso_Stick", "CheckBox", nullptr));
        CAN_communication_test_1_checkBox->setText(QApplication::translate("Senso_Stick", "CheckBox", nullptr));
        CAN_status_Error_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        CAN_communication_Error_1_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        CAN_init_Error_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Start_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Stop_Peak_CANpushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Status_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Error_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        State_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Statemachine_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Check_Motorencoder_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Motorencoderpos_1_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Motorencoderpos_value_1_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        ReferenceDrive_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Encoder_Index_1_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Encoder_Indexvalue_1_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Normal_Mode_Off_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        CAN_init_checkBox->setText(QApplication::translate("Senso_Stick", "CheckBox", nullptr));
        Peak_CAN_start_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Stop_Senso_Stick_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Senso_Stick_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        SensoStick_CAN_Comm_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        CAN_communication_test_2_checkBox->setText(QApplication::translate("Senso_Stick", "CheckBox", nullptr));
        CAN_communication_test_3_checkBox->setText(QApplication::translate("Senso_Stick", "CheckBox", nullptr));
        CAN_communication_Error_2_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        CAN_communication_Error_3_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Motorencoderpos_2_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Motorencoderpos_3_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Motorencoderpos_value_2_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Motorencoderpos_value_3_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Encoder_Index_2_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Encoder_Index_3_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Encoder_Indexvalue_2_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Encoder_Indexvalue_3_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Clear_Status_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Clear_Error_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Normal_Mode_Ready_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Normal_Mode_On_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        Enable_Button_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Normal_Mode_Spring_Damper_pushButton->setText(QApplication::translate("Senso_Stick", "PushButton", nullptr));
        y_Spring_Stiffness_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        y_Friction_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        y_Damping_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        y_Torque_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Torque_Limit_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Peak_Torque_Limit_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Torque_Limit_value_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Peak_Torque_Limit_value_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        General_Torque_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Mini_Stick_left_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Mini_Stick_middle_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Mini_Stick_right_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Mini_Stick_up_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Mini_Stick_down_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Flip_Switch_left_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Flip_Switch_middle_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Flip_Switch_right_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Front_Button_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Enable_Button_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        Front_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        Rear_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        y_settings_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        x_Torque_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        x_Friction_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        x_Spring_Stiffness_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        x_Damping_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        x_settings_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        z_Friction_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        z_Spring_Stiffness_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        z_Damping_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        z_settings_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        z_Torque_label->setText(QApplication::translate("Senso_Stick", "TextLabel", nullptr));
        switch_off_acknowledge_button_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
        external_control_radioButton->setText(QApplication::translate("Senso_Stick", "RadioButton", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Senso_Stick: public Ui_Senso_Stick {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SENSO_STICK_H
